/*
 * generated by Xtext 2.39.0
 */
package org.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OrkaDslStandaloneSetup extends OrkaDslStandaloneSetupGenerated {

	public static void doSetup() {
		new OrkaDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
