/*
 * generated by Xtext 2.39.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.OrkaDslRuntimeModule;
import org.xtext.OrkaDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OrkaDslIdeSetup extends OrkaDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OrkaDslRuntimeModule(), new OrkaDslIdeModule()));
	}
	
}
