/*
 * generated by Xtext 2.39.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OrkaDslUiModule extends AbstractOrkaDslUiModule {

	public OrkaDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
